name: build-nsis

# on: [push, pull_request, workflow_dispatch]
on: [workflow_dispatch]

jobs:

  build-nsis-exe:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        choco install 7zip curl
        curl -O https://nsis.sourceforge.io/mediawiki/images/1/18/NsProcess.zip
        curl -O https://nsis.sourceforge.io/mediawiki/images/c/c9/Inetc.zip
        curl -O https://nsis.sourceforge.io/mediawiki/images/5/5a/NSISunzU.zip
        curl -O https://nsis.sourceforge.io/mediawiki/images/1/11/Nsis7z_921.zip
        ls -R
        7z x -o"${{ github.workspace }}\NSIS_Plugins" "${{ github.workspace }}\*.zip"
        Remove-Item NSIS_Plugins\Plugin\nsProcess.dll
        Move-Item -Path NSIS_Plugins\Plugin\nsProcessW.dll -Destination NSIS_Plugins\Plugins\amd64-unicode\nsProcess.dll
        Move-Item -Path "NSIS_Plugins\Plugin unicode\nsisunz.dll" -Destination NSIS_Plugins\Plugins\amd64-unicode\nsisunz.dll
        Move-Item -Path NSIS_Plugins\_release_unicode\nsis7z.dll -Destination NSIS_Plugins\Plugins\amd64-unicode\nsis7z.dll
    - name: list dirs
      run: |
        ls -R
    - name: Create installer
      uses: joncloud/makensis-action@v4.1
      with:
        arguments: "/V4"
        script-file: "Build123dPortableSetup.nsi"
        additional-plugin-paths: |
          ${{ github.workspace }}\NSIS_Plugins\Plugin
          ${{ github.workspace }}\NSIS_Plugins\Plugins

          
        # ${{ github.workspace }}\NSIS_Plugins\_release_unicode
        # NsProcess\Plugin\
        # Inetc\Plugins\
        # Nsisunz\nsisunz\Release\
        # Nsis7z_921\

  # TODO: publishing        
  # publish-nsis:
